{
 "title": "Production Environment - Traffic acquisition metrics Categorised",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  { "title": "User Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "accountId": "accounts/244647801",
     "cacheDurationSeconds": 300,
     "metrics": [
      "totalUsers",
      "newUsers"
     ],
     "mode": "table",
     "selectedMetrics": [
      {
       "description": "The number of distinct users who have logged at least one event, regardless of whether the site or app was in use when that event was logged.",
       "label": "Total users",
       "value": "totalUsers"
      },
      {
       "description": "The number of users who interacted with your site or launched your app for the first time (event triggered: first_open or first_visit).",
       "label": "New users",
       "value": "newUsers"
      }
     ],
     "timezone": "Etc/GMT",
     "version": "v4",
     "webPropertyId": "properties/336167131"
    }
   ]
  },
  {
   "title": "Users by Town or City",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "accountId": "accounts/244647801",
     "cacheDurationSeconds": 300,
     "dimensions": [ "city" ],
     "metrics": [ "totalUsers" ],
     "mode": "table",
     "selectedDimensions": [
      {
       "description": "The city from which the user activity originated.",
       "label": "City",
       "value": "city"
      }
     ],
     "selectedMetrics": [
      {
       "description": "The number of distinct users who have logged at least one event, regardless of whether the site or app was in use when that event was logged.",
       "label": "Total users",
       "value": "totalUsers"
      }
     ],
     "timezone": "Etc/GMT",
     "version": "v4",
     "webPropertyId": "properties/336167131"
    }
   ]
  },
  {
   "title": "Month on Month Progress",
   "type": "barchart",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "accountId": "accounts/244647801",
     "cacheDurationSeconds": 300,
     "dimensions": [ "yearMonth" ],
     "metrics": [
      "newUsers",
      "totalUsers"
     ],
     "mode": "table",
     "selectedDimensions": [
      {
       "description": "The combined values of year and month. Example values include 202212 or 202301.",
       "label": "Year month",
       "value": "yearMonth"
      }
     ],
     "selectedMetrics": [
      {
       "description": "The number of users who interacted with your site or launched your app for the first time (event triggered: first_open or first_visit).",
       "label": "New users",
       "value": "newUsers"
      },
      {
       "description": "The number of distinct users who have logged at least one event, regardless of whether the site or app was in use when that event was logged.",
       "label": "Total users",
       "value": "totalUsers"
      }
     ],
     "timezone": "Etc/GMT",
     "version": "v4",
     "webPropertyId": "properties/336167131"
    }
   ]
  },
  { "title": "User Engagement ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Average Session Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "accountId": "accounts/244647801",
     "cacheDurationSeconds": 300,
     "metrics": [ "averageSessionDuration" ],
     "mode": "table",
     "selectedMetrics": [
      {
       "description": "The average duration (in seconds) of users' sessions.",
       "label": "Average session duration",
       "value": "averageSessionDuration"
      }
     ],
     "timezone": "Etc/GMT",
     "version": "v4",
     "webPropertyId": "properties/336167131"
    }
   ]
  },
  {
   "title": "Engagement Rate ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "accountId": "accounts/244647801",
     "cacheDurationSeconds": 300,
     "metrics": [ "engagementRate" ],
     "mode": "table",
     "selectedMetrics": [
      {
       "description": "The percentage of engaged sessions (Engaged sessions divided by Sessions). This metric is returned as a fraction; for example, 0.7239 means 72.39% of sessions were engaged sessions.",
       "label": "Engagement rate",
       "value": "engagementRate"
      }
     ],
     "timezone": "Etc/GMT",
     "version": "v4",
     "webPropertyId": "properties/336167131"
    }
   ]
  },
  {
   "title": "Conversions ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "accountId": "accounts/244647801",
     "cacheDurationSeconds": 300,
     "dimensions": [ "linkUrl" ],
     "metrics": [ "conversions" ],
     "mode": "table",
     "selectedDimensions": [
      {
       "description": "The full url for an outbound link or file download. For example if a user clicks a link '<a href=\"https://www.youtube.com/results?search_query=analytics\">', this dimension will return 'https://www.youtube.com/results?search_query=analytics'. Automatically populated if Enhanced Measurement is enabled. Populated by the event parameter 'link_url'.",
       "label": "Link URL",
       "value": "linkUrl"
      }
     ],
     "selectedMetrics": [
      {
       "description": "The count of conversion events. Events are marked as conversions at collection time; changes to an event's conversion marking apply going forward. You can mark any event as a conversion in Google Analytics, and some events (i.e. first_open, purchase) are marked as conversions by default. To learn more, see <https://support.google.com/analytics/answer/9267568>.",
       "label": "Conversions",
       "value": "conversions"
      }
     ],
     "timezone": "Etc/GMT",
     "version": "v4",
     "webPropertyId": "properties/336167131"
    },
    {
     "accountId": "accounts/244647801",
     "cacheDurationSeconds": 300,
     "dimensions": [ "linkUrl" ],
     "metrics": [ "conversions" ],
     "mode": "table",
     "selectedDimensions": [
      {
       "description": "The full url for an outbound link or file download. For example if a user clicks a link '<a href=\"https://www.youtube.com/results?search_query=analytics\">', this dimension will return 'https://www.youtube.com/results?search_query=analytics'. Automatically populated if Enhanced Measurement is enabled. Populated by the event parameter 'link_url'.",
       "label": "Link URL",
       "value": "linkUrl"
      }
     ],
     "selectedMetrics": [
      {
       "description": "The count of conversion events. Events are marked as conversions at collection time; changes to an event's conversion marking apply going forward. You can mark any event as a conversion in Google Analytics, and some events (i.e. first_open, purchase) are marked as conversions by default. To learn more, see <https://support.google.com/analytics/answer/9267568>.",
       "label": "Conversions",
       "value": "conversions"
      }
     ],
     "timezone": "Etc/GMT",
     "version": "v4",
     "webPropertyId": "properties/336167131"
    },
    {
     "accountId": "accounts/244647801",
     "cacheDurationSeconds": 300,
     "dimensions": [ "linkUrl" ],
     "metrics": [
      "conversions",
      "engagedSessions"
     ],
     "mode": "table",
     "selectedDimensions": [
      {
       "description": "The full url for an outbound link or file download. For example if a user clicks a link '<a href=\"https://www.youtube.com/results?search_query=analytics\">', this dimension will return 'https://www.youtube.com/results?search_query=analytics'. Automatically populated if Enhanced Measurement is enabled. Populated by the event parameter 'link_url'.",
       "label": "Link URL",
       "value": "linkUrl"
      }
     ],
     "selectedMetrics": [
      {
       "description": "The count of conversion events. Events are marked as conversions at collection time; changes to an event's conversion marking apply going forward. You can mark any event as a conversion in Google Analytics, and some events (i.e. first_open, purchase) are marked as conversions by default. To learn more, see <https://support.google.com/analytics/answer/9267568>.",
       "label": "Conversions",
       "value": "conversions"
      },
      {
       "description": "The number of sessions that lasted longer than 10 seconds, or had a conversion event, or had 2 or more screen views.",
       "label": "Engaged sessions",
       "value": "engagedSessions"
      }
     ],
     "timezone": "Etc/GMT",
     "version": "v4",
     "webPropertyId": "properties/336167131"
    }
   ]
  },
  {
   "title": "Link Conversion Breakdown",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "accountId": "accounts/244647801",
     "cacheDurationSeconds": 300,
     "dimensions": [ "linkUrl" ],
     "metrics": [ "conversions" ],
     "mode": "table",
     "selectedDimensions": [
      {
       "description": "The full url for an outbound link or file download. For example if a user clicks a link '<a href=\"https://www.youtube.com/results?search_query=analytics\">', this dimension will return 'https://www.youtube.com/results?search_query=analytics'. Automatically populated if Enhanced Measurement is enabled. Populated by the event parameter 'link_url'.",
       "label": "Link URL",
       "value": "linkUrl"
      }
     ],
     "selectedMetrics": [
      {
       "description": "The count of conversion events. Events are marked as conversions at collection time; changes to an event's conversion marking apply going forward. You can mark any event as a conversion in Google Analytics, and some events (i.e. first_open, purchase) are marked as conversions by default. To learn more, see <https://support.google.com/analytics/answer/9267568>.",
       "label": "Conversions",
       "value": "conversions"
      }
     ],
     "timezone": "Etc/GMT",
     "version": "v4",
     "webPropertyId": "properties/336167131"
    }
   ]
  },
  {
   "title": "Conversions to Development Programme Provider Sites",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "accountId": "accounts/244647801",
     "cacheDurationSeconds": 300,
     "dimensions": [ "linkUrl" ],
     "metrics": [ "conversions" ],
     "mode": "table",
     "selectedDimensions": [
      {
       "description": "The full url for an outbound link or file download. For example if a user clicks a link '<a href=\"https://www.youtube.com/results?search_query=analytics\">', this dimension will return 'https://www.youtube.com/results?search_query=analytics'. Automatically populated if Enhanced Measurement is enabled. Populated by the event parameter 'link_url'.",
       "label": "Link URL",
       "value": "linkUrl"
      }
     ],
     "selectedMetrics": [
      {
       "description": "The count of conversion events. Events are marked as conversions at collection time; changes to an event's conversion marking apply going forward. You can mark any event as a conversion in Google Analytics, and some events (i.e. first_open, purchase) are marked as conversions by default. To learn more, see <https://support.google.com/analytics/answer/9267568>.",
       "label": "Conversions",
       "value": "conversions"
      }
     ],
     "timezone": "Etc/GMT",
     "version": "v4",
     "webPropertyId": "properties/336167131"
    }
   ]
  },
  {
   "title": "Conversions to Feedback Link",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "accountId": "accounts/244647801",
     "cacheDurationSeconds": 300,
     "dimensions": [ "linkUrl" ],
     "metrics": [ "conversions" ],
     "mode": "table",
     "selectedDimensions": [
      {
       "description": "The full url for an outbound link or file download. For example if a user clicks a link '<a href=\"https://www.youtube.com/results?search_query=analytics\">', this dimension will return 'https://www.youtube.com/results?search_query=analytics'. Automatically populated if Enhanced Measurement is enabled. Populated by the event parameter 'link_url'.",
       "label": "Link URL",
       "value": "linkUrl"
      }
     ],
     "selectedMetrics": [
      {
       "description": "The count of conversion events. Events are marked as conversions at collection time; changes to an event's conversion marking apply going forward. You can mark any event as a conversion in Google Analytics, and some events (i.e. first_open, purchase) are marked as conversions by default. To learn more, see <https://support.google.com/analytics/answer/9267568>.",
       "label": "Conversions",
       "value": "conversions"
      }
     ],
     "timezone": "Etc/GMT",
     "version": "v4",
     "webPropertyId": "properties/336167131"
    }
   ]
  },
  { "title": "User Insights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Active users",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "accountId": "accounts/244647801",
     "cacheDurationSeconds": 300,
     "metrics": [ "activeUsers" ],
     "mode": "table",
     "selectedMetrics": [
      {
       "description": "The number of distinct users who visited your site or app.",
       "label": "Active users",
       "value": "activeUsers"
      }
     ],
     "selectedTimeDimensions": {
      "description": "The combined values of date, hour, and minute formatted as YYYYMMDDHHMM.",
      "label": "Date hour and minute",
      "value": "dateHourMinute"
     },
     "timeDimension": "dateHourMinute",
     "timezone": "Etc/GMT",
     "version": "v4",
     "webPropertyId": "properties/336167131"
    }
   ]
  },
  {
   "title": "Most Visited Pages",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "accountId": "accounts/244647801",
     "cacheDurationSeconds": 300,
     "dimensions": [ "unifiedScreenClass" ],
     "metrics": [ "totalUsers" ],
     "mode": "table",
     "selectedDimensions": [
      {
       "description": "The page title (web) or screen class (app) on which the event was logged.",
       "label": "Page title and screen class",
       "value": "unifiedScreenClass"
      }
     ],
     "selectedMetrics": [
      {
       "description": "The number of distinct users who have logged at least one event, regardless of whether the site or app was in use when that event was logged.",
       "label": "Total users",
       "value": "totalUsers"
      }
     ],
     "timezone": "Etc/GMT",
     "version": "v4",
     "webPropertyId": "properties/336167131"
    }
   ]
  },
  {
   "title": "Most popular days of the week",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "accountId": "accounts/244647801",
     "cacheDurationSeconds": 300,
     "dimensions": [
      "dayOfWeek",
      "dayOfWeekName"
     ],
     "metrics": [ "sessions" ],
     "mode": "table",
     "selectedDimensions": [
      {
       "description": "The integer day of the week. It returns values in the range [0,6] with Sunday as the first day of the week.",
       "label": "Day of week",
       "value": "dayOfWeek"
      },
      {
       "description": "The day of the week in English. This dimension has values of Sunday, Monday, etc.",
       "label": "Day of week name",
       "value": "dayOfWeekName"
      }
     ],
     "selectedMetrics": [
      {
       "description": "The number of sessions that began on your site or app (event triggered: session_start).",
       "label": "Sessions",
       "value": "sessions"
      }
     ],
     "timezone": "Etc/GMT",
     "version": "v4",
     "webPropertyId": "properties/336167131"
    }
   ]
  },
  {
   "title": "Most popular hours of the day",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "accountId": "accounts/244647801",
     "cacheDurationSeconds": 300,
     "dimensions": [ "hour" ],
     "metrics": [ "sessions" ],
     "mode": "table",
     "selectedDimensions": [
      {
       "description": "The two-digit hour of the day that the event was logged. This dimension ranges from 0-23 and is reported in your property's timezone.",
       "label": "Hour",
       "value": "hour"
      }
     ],
     "selectedMetrics": [
      {
       "description": "The number of sessions that began on your site or app (event triggered: session_start).",
       "label": "Sessions",
       "value": "sessions"
      }
     ],
     "timezone": "Etc/GMT",
     "version": "v4",
     "webPropertyId": "properties/336167131"
    }
   ]
  },
  { "title": "Tech Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Top Ten Users by Screen Resolution",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "accountId": "accounts/244647801",
     "cacheDurationSeconds": 300,
     "dimensions": [ "screenResolution" ],
     "metrics": [ "totalUsers" ],
     "mode": "table",
     "selectedDimensions": [
      {
       "description": "The screen resolution of the user's monitor. For example, 1920x1080.",
       "label": "Screen resolution",
       "value": "screenResolution"
      }
     ],
     "selectedMetrics": [
      {
       "description": "The number of distinct users who have logged at least one event, regardless of whether the site or app was in use when that event was logged.",
       "label": "Total users",
       "value": "totalUsers"
      }
     ],
     "timezone": "Etc/GMT",
     "version": "v4",
     "webPropertyId": "properties/336167131"
    }
   ]
  },
  {
   "title": "Top Ten Users by Screen Resolution",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "accountId": "accounts/244647801",
     "cacheDurationSeconds": 300,
     "dimensions": [ "screenResolution" ],
     "metrics": [ "totalUsers" ],
     "mode": "table",
     "selectedDimensions": [
      {
       "description": "The screen resolution of the user's monitor. For example, 1920x1080.",
       "label": "Screen resolution",
       "value": "screenResolution"
      }
     ],
     "selectedMetrics": [
      {
       "description": "The number of distinct users who have logged at least one event, regardless of whether the site or app was in use when that event was logged.",
       "label": "Total users",
       "value": "totalUsers"
      }
     ],
     "timezone": "Etc/GMT",
     "version": "v4",
     "webPropertyId": "properties/336167131"
    }
   ]
  },
  {
   "title": "Users by Operating System",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "targets": [
    {
     "accountId": "accounts/244647801",
     "cacheDurationSeconds": 300,
     "dimensions": [ "operatingSystem" ],
     "metrics": [ "totalUsers" ],
     "mode": "table",
     "selectedDimensions": [
      {
       "description": "The operating systems used by visitors to your app or website. Includes desktop and mobile operating systems such as Windows and Android.",
       "label": "Operating system",
       "value": "operatingSystem"
      }
     ],
     "selectedMetrics": [
      {
       "description": "The number of distinct users who have logged at least one event, regardless of whether the site or app was in use when that event was logged.",
       "label": "Total users",
       "value": "totalUsers"
      }
     ],
     "timezone": "Etc/GMT",
     "version": "v4",
     "webPropertyId": "properties/336167131"
    }
   ]
  },
  {
   "title": "Users by Operating System",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "targets": [
    {
     "accountId": "accounts/244647801",
     "cacheDurationSeconds": 300,
     "dimensions": [ "operatingSystem" ],
     "metrics": [ "totalUsers" ],
     "mode": "table",
     "selectedDimensions": [
      {
       "description": "The operating systems used by visitors to your app or website. Includes desktop and mobile operating systems such as Windows and Android.",
       "label": "Operating system",
       "value": "operatingSystem"
      }
     ],
     "selectedMetrics": [
      {
       "description": "The number of distinct users who have logged at least one event, regardless of whether the site or app was in use when that event was logged.",
       "label": "Total users",
       "value": "totalUsers"
      }
     ],
     "timezone": "Etc/GMT",
     "version": "v4",
     "webPropertyId": "properties/336167131"
    }
   ]
  },
  {
   "title": "Users by Browser",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "targets": [
    {
     "accountId": "accounts/244647801",
     "cacheDurationSeconds": 300,
     "dimensions": [ "browser" ],
     "metrics": [ "totalUsers" ],
     "mode": "table",
     "selectedDimensions": [
      {
       "description": "The browsers used to view your website.",
       "label": "Browser",
       "value": "browser"
      }
     ],
     "selectedMetrics": [
      {
       "description": "The number of distinct users who have logged at least one event, regardless of whether the site or app was in use when that event was logged.",
       "label": "Total users",
       "value": "totalUsers"
      }
     ],
     "timezone": "Etc/GMT",
     "version": "v4",
     "webPropertyId": "properties/336167131"
    }
   ]
  },
  {
   "title": "Users by Browser",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "targets": [
    {
     "accountId": "accounts/244647801",
     "cacheDurationSeconds": 300,
     "dimensions": [ "browser" ],
     "metrics": [ "totalUsers" ],
     "mode": "table",
     "selectedDimensions": [
      {
       "description": "The browsers used to view your website.",
       "label": "Browser",
       "value": "browser"
      }
     ],
     "selectedMetrics": [
      {
       "description": "The number of distinct users who have logged at least one event, regardless of whether the site or app was in use when that event was logged.",
       "label": "Total users",
       "value": "totalUsers"
      }
     ],
     "timezone": "Etc/GMT",
     "version": "v4",
     "webPropertyId": "properties/336167131"
    }
   ]
  },
  {
   "title": "Users by Channel",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "targets": [
    {
     "accountId": "accounts/244647801",
     "cacheDurationSeconds": 300,
     "dimensions": [ "sessionSourceMedium" ],
     "metrics": [ "totalUsers" ],
     "mode": "table",
     "selectedDimensions": [
      {
       "description": "The combined values of the dimensions 'sessionSource' and 'sessionMedium'.",
       "label": "Session source / medium",
       "value": "sessionSourceMedium"
      }
     ],
     "selectedMetrics": [
      {
       "description": "The number of distinct users who have logged at least one event, regardless of whether the site or app was in use when that event was logged.",
       "label": "Total users",
       "value": "totalUsers"
      }
     ],
     "timezone": "Etc/GMT",
     "version": "v4",
     "webPropertyId": "properties/336167131"
    }
   ]
  },
  {
   "title": "Users by Device",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "accountId": "accounts/244647801",
     "cacheDurationSeconds": 300,
     "dimensions": [ "platformDeviceCategory" ],
     "metrics": [ "totalUsers" ],
     "mode": "time series",
     "selectedDimensions": [
      {
       "description": "The platform and type of device on which your website or mobile app ran. (example: Android / mobile)",
       "label": "Platform / device category",
       "value": "platformDeviceCategory"
      }
     ],
     "selectedMetrics": [
      {
       "description": "The number of distinct users who have logged at least one event, regardless of whether the site or app was in use when that event was logged.",
       "label": "Total users",
       "value": "totalUsers"
      }
     ],
     "timezone": "Etc/GMT",
     "version": "v4",
     "webPropertyId": "properties/336167131"
    }
   ]
  },
  { "title": "Deep Dive Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "Users on Production",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "targets": [
    {
     "accountId": "accounts/244647801",
     "cacheDurationSeconds": 300,
     "metrics": [
      "activeUsers",
      "totalUsers",
      "newUsers"
     ],
     "mode": "time series",
     "selectedMetrics": [
      {
       "description": "The number of distinct users who visited your site or app.",
       "label": "Active users",
       "value": "activeUsers"
      },
      {
       "description": "The number of distinct users who have logged at least one event, regardless of whether the site or app was in use when that event was logged.",
       "label": "Total users",
       "value": "totalUsers"
      },
      {
       "description": "The number of users who interacted with your site or launched your app for the first time (event triggered: first_open or first_visit).",
       "label": "New users",
       "value": "newUsers"
      }
     ],
     "selectedTimeDimensions": {
      "description": "The date of the event, formatted as YYYYMMDD.",
      "label": "Date",
      "value": "date"
     },
     "timeDimension": "date",
     "timezone": "Etc/GMT",
     "version": "v4",
     "webPropertyId": "properties/336167131"
    }
   ]
  },
  {
   "title": "Most Visited Pages",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "targets": [
    {
     "accountId": "accounts/244647801",
     "cacheDurationSeconds": 300,
     "dimensions": [ "unifiedScreenClass" ],
     "metrics": [
      "screenPageViews",
      "totalUsers",
      "screenPageViewsPerUser",
      "engagementRate",
      "eventCount",
      "conversions"
     ],
     "mode": "table",
     "selectedDimensions": [
      {
       "description": "The page title (web) or screen class (app) on which the event was logged.",
       "label": "Page title and screen class",
       "value": "unifiedScreenClass"
      }
     ],
     "selectedMetrics": [
      {
       "description": "The number of app screens or web pages your users viewed. Repeated views of a single page or screen are counted. (screen_view + page_view events).",
       "label": "Views",
       "value": "screenPageViews"
      },
      {
       "description": "The number of distinct users who have logged at least one event, regardless of whether the site or app was in use when that event was logged.",
       "label": "Total users",
       "value": "totalUsers"
      },
      {
       "description": "The number of app screens or web pages your users viewed per active user. Repeated views of a single page or screen are counted. (screen_view + page_view events) / active users.",
       "label": "Views per user",
       "value": "screenPageViewsPerUser"
      },
      {
       "description": "The percentage of engaged sessions (Engaged sessions divided by Sessions). This metric is returned as a fraction; for example, 0.7239 means 72.39% of sessions were engaged sessions.",
       "label": "Engagement rate",
       "value": "engagementRate"
      },
      { "description": "The count of events.", "label": "Event count", "value": "eventCount" },
      {
       "description": "The count of conversion events. Events are marked as conversions at collection time; changes to an event's conversion marking apply going forward. You can mark any event as a conversion in Google Analytics, and some events (i.e. first_open, purchase) are marked as conversions by default. To learn more, see <https://support.google.com/analytics/answer/9267568>.",
       "label": "Conversions",
       "value": "conversions"
      }
     ],
     "timezone": "Etc/GMT",
     "version": "v4",
     "webPropertyId": "properties/336167131"
    }
   ]
  },
  {
   "title": "Engagement Time (Target 3 to 5 minutes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "targets": [
    {
     "accountId": "accounts/244647801",
     "cacheDurationSeconds": 300,
     "metrics": [ "userEngagementDuration" ],
     "mode": "time series",
     "selectedMetrics": [
      {
       "description": "The total amount of time (in seconds) your website or app was in the foreground of users' devices.",
       "label": "User engagement",
       "value": "userEngagementDuration"
      }
     ],
     "selectedTimeDimensions": {
      "description": "The date of the event, formatted as YYYYMMDD.",
      "label": "Date",
      "value": "date"
     },
     "timeDimension": "date",
     "timezone": "Etc/GMT",
     "version": "v4",
     "webPropertyId": "properties/336167131"
    }
   ]
  },
  {
   "title": "Development programmes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
   "targets": [
    {
     "accountId": "accounts/244647801",
     "cacheDurationSeconds": 300,
     "dimensions": [ "unifiedScreenClass" ],
     "metrics": [
      "screenPageViews",
      "totalUsers",
      "screenPageViewsPerUser",
      "engagementRate",
      "eventCount",
      "conversions"
     ],
     "mode": "table",
     "selectedDimensions": [
      {
       "description": "The page title (web) or screen class (app) on which the event was logged.",
       "label": "Page title and screen class",
       "value": "unifiedScreenClass"
      }
     ],
     "selectedMetrics": [
      {
       "description": "The number of app screens or web pages your users viewed. Repeated views of a single page or screen are counted. (screen_view + page_view events).",
       "label": "Views",
       "value": "screenPageViews"
      },
      {
       "description": "The number of distinct users who have logged at least one event, regardless of whether the site or app was in use when that event was logged.",
       "label": "Total users",
       "value": "totalUsers"
      },
      {
       "description": "The number of app screens or web pages your users viewed per active user. Repeated views of a single page or screen are counted. (screen_view + page_view events) / active users.",
       "label": "Views per user",
       "value": "screenPageViewsPerUser"
      },
      {
       "description": "The percentage of engaged sessions (Engaged sessions divided by Sessions). This metric is returned as a fraction; for example, 0.7239 means 72.39% of sessions were engaged sessions.",
       "label": "Engagement rate",
       "value": "engagementRate"
      },
      { "description": "The count of events.", "label": "Event count", "value": "eventCount" },
      {
       "description": "The count of conversion events. Events are marked as conversions at collection time; changes to an event's conversion marking apply going forward. You can mark any event as a conversion in Google Analytics, and some events (i.e. first_open, purchase) are marked as conversions by default. To learn more, see <https://support.google.com/analytics/answer/9267568>.",
       "label": "Conversions",
       "value": "conversions"
      }
     ],
     "timezone": "Etc/GMT",
     "version": "v4",
     "webPropertyId": "properties/336167131"
    }
   ]
  },
  {
   "title": "Conversion Metrics over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
   "targets": [
    {
     "accountId": "accounts/244647801",
     "cacheDurationSeconds": 300,
     "metrics": [ "conversions" ],
     "mode": "time series",
     "selectedMetrics": [
      {
       "description": "The count of conversion events. Events are marked as conversions at collection time; changes to an event's conversion marking apply going forward. You can mark any event as a conversion in Google Analytics, and some events (i.e. first_open, purchase) are marked as conversions by default. To learn more, see <https://support.google.com/analytics/answer/9267568>.",
       "label": "Conversions",
       "value": "conversions"
      }
     ],
     "selectedTimeDimensions": {
      "description": "The date of the event, formatted as YYYYMMDD.",
      "label": "Date",
      "value": "date"
     },
     "timeDimension": "date",
     "timezone": "Etc/GMT",
     "version": "v4",
     "webPropertyId": "properties/336167131"
    }
   ]
  },
  {
   "title": "Explore roles",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
   "targets": [
    {
     "accountId": "accounts/244647801",
     "cacheDurationSeconds": 300,
     "dimensions": [ "unifiedScreenClass" ],
     "metrics": [
      "screenPageViews",
      "totalUsers",
      "screenPageViewsPerUser",
      "engagementRate",
      "eventCount",
      "conversions"
     ],
     "mode": "table",
     "selectedDimensions": [
      {
       "description": "The page title (web) or screen class (app) on which the event was logged.",
       "label": "Page title and screen class",
       "value": "unifiedScreenClass"
      }
     ],
     "selectedMetrics": [
      {
       "description": "The number of app screens or web pages your users viewed. Repeated views of a single page or screen are counted. (screen_view + page_view events).",
       "label": "Views",
       "value": "screenPageViews"
      },
      {
       "description": "The number of distinct users who have logged at least one event, regardless of whether the site or app was in use when that event was logged.",
       "label": "Total users",
       "value": "totalUsers"
      },
      {
       "description": "The number of app screens or web pages your users viewed per active user. Repeated views of a single page or screen are counted. (screen_view + page_view events) / active users.",
       "label": "Views per user",
       "value": "screenPageViewsPerUser"
      },
      {
       "description": "The percentage of engaged sessions (Engaged sessions divided by Sessions). This metric is returned as a fraction; for example, 0.7239 means 72.39% of sessions were engaged sessions.",
       "label": "Engagement rate",
       "value": "engagementRate"
      },
      { "description": "The count of events.", "label": "Event count", "value": "eventCount" },
      {
       "description": "The count of conversion events. Events are marked as conversions at collection time; changes to an event's conversion marking apply going forward. You can mark any event as a conversion in Google Analytics, and some events (i.e. first_open, purchase) are marked as conversions by default. To learn more, see <https://support.google.com/analytics/answer/9267568>.",
       "label": "Conversions",
       "value": "conversions"
      }
     ],
     "timezone": "Etc/GMT",
     "version": "v4",
     "webPropertyId": "properties/336167131"
    }
   ]
  },
  {
   "title": "User Engagement Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 127 },
   "targets": [
    {
     "accountId": "accounts/244647801",
     "cacheDurationSeconds": 300,
     "metrics": [ "engagementRate" ],
     "mode": "time series",
     "selectedMetrics": [
      {
       "description": "The percentage of engaged sessions (Engaged sessions divided by Sessions). This metric is returned as a fraction; for example, 0.7239 means 72.39% of sessions were engaged sessions.",
       "label": "Engagement rate",
       "value": "engagementRate"
      }
     ],
     "selectedTimeDimensions": {
      "description": "The date of the event, formatted as YYYYMMDD.",
      "label": "Date",
      "value": "date"
     },
     "timeDimension": "date",
     "timezone": "Etc/GMT",
     "version": "v4",
     "webPropertyId": "properties/336167131"
    }
   ]
  },
  {
   "title": "Explore areas of practice",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 127 },
   "targets": [
    {
     "accountId": "accounts/244647801",
     "cacheDurationSeconds": 300,
     "dimensions": [ "unifiedScreenClass" ],
     "metrics": [
      "screenPageViews",
      "totalUsers",
      "screenPageViewsPerUser",
      "engagementRate",
      "eventCount",
      "conversions"
     ],
     "mode": "table",
     "selectedDimensions": [
      {
       "description": "The page title (web) or screen class (app) on which the event was logged.",
       "label": "Page title and screen class",
       "value": "unifiedScreenClass"
      }
     ],
     "selectedMetrics": [
      {
       "description": "The number of app screens or web pages your users viewed. Repeated views of a single page or screen are counted. (screen_view + page_view events).",
       "label": "Views",
       "value": "screenPageViews"
      },
      {
       "description": "The number of distinct users who have logged at least one event, regardless of whether the site or app was in use when that event was logged.",
       "label": "Total users",
       "value": "totalUsers"
      },
      {
       "description": "The number of app screens or web pages your users viewed per active user. Repeated views of a single page or screen are counted. (screen_view + page_view events) / active users.",
       "label": "Views per user",
       "value": "screenPageViewsPerUser"
      },
      {
       "description": "The percentage of engaged sessions (Engaged sessions divided by Sessions). This metric is returned as a fraction; for example, 0.7239 means 72.39% of sessions were engaged sessions.",
       "label": "Engagement rate",
       "value": "engagementRate"
      },
      { "description": "The count of events.", "label": "Event count", "value": "eventCount" },
      {
       "description": "The count of conversion events. Events are marked as conversions at collection time; changes to an event's conversion marking apply going forward. You can mark any event as a conversion in Google Analytics, and some events (i.e. first_open, purchase) are marked as conversions by default. To learn more, see <https://support.google.com/analytics/answer/9267568>.",
       "label": "Conversions",
       "value": "conversions"
      }
     ],
     "timezone": "Etc/GMT",
     "version": "v4",
     "webPropertyId": "properties/336167131"
    }
   ]
  },
  {
   "title": "Individual Page Bounce Rate",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "accountId": "accounts/244647801",
     "cacheDurationSeconds": 300,
     "dimensions": [ "pageTitle" ],
     "metrics": [ "bounceRate" ],
     "mode": "table",
     "selectedDimensions": [
      {
       "description": "The web page titles used on your site.",
       "label": "Page title",
       "value": "pageTitle"
      }
     ],
     "selectedMetrics": [
      {
       "description": "The percentage of sessions that were not engaged ((Sessions Minus Engaged sessions) divided by Sessions). This metric is returned as a fraction; for example, 0.2761 means 27.61% of sessions were bounces.",
       "label": "Bounce rate",
       "value": "bounceRate"
      }
     ],
     "timezone": "Etc/GMT",
     "version": "v4",
     "webPropertyId": "properties/336167131"
    }
   ]
  },
  {
   "title": "Career stages",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
   "targets": [
    {
     "accountId": "accounts/244647801",
     "cacheDurationSeconds": 300,
     "dimensions": [ "unifiedScreenClass" ],
     "metrics": [
      "screenPageViews",
      "totalUsers",
      "screenPageViewsPerUser",
      "engagementRate",
      "eventCount",
      "conversions"
     ],
     "mode": "table",
     "selectedDimensions": [
      {
       "description": "The page title (web) or screen class (app) on which the event was logged.",
       "label": "Page title and screen class",
       "value": "unifiedScreenClass"
      }
     ],
     "selectedMetrics": [
      {
       "description": "The number of app screens or web pages your users viewed. Repeated views of a single page or screen are counted. (screen_view + page_view events).",
       "label": "Views",
       "value": "screenPageViews"
      },
      {
       "description": "The number of distinct users who have logged at least one event, regardless of whether the site or app was in use when that event was logged.",
       "label": "Total users",
       "value": "totalUsers"
      },
      {
       "description": "The number of app screens or web pages your users viewed per active user. Repeated views of a single page or screen are counted. (screen_view + page_view events) / active users.",
       "label": "Views per user",
       "value": "screenPageViewsPerUser"
      },
      {
       "description": "The percentage of engaged sessions (Engaged sessions divided by Sessions). This metric is returned as a fraction; for example, 0.7239 means 72.39% of sessions were engaged sessions.",
       "label": "Engagement rate",
       "value": "engagementRate"
      },
      { "description": "The count of events.", "label": "Event count", "value": "eventCount" },
      {
       "description": "The count of conversion events. Events are marked as conversions at collection time; changes to an event's conversion marking apply going forward. You can mark any event as a conversion in Google Analytics, and some events (i.e. first_open, purchase) are marked as conversions by default. To learn more, see <https://support.google.com/analytics/answer/9267568>.",
       "label": "Conversions",
       "value": "conversions"
      }
     ],
     "timezone": "Etc/GMT",
     "version": "v4",
     "webPropertyId": "properties/336167131"
    }
   ]
  },
  {
   "title": "Users by Town or City",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 143 },
   "targets": [
    {
     "accountId": "accounts/244647801",
     "cacheDurationSeconds": 300,
     "dimensions": [ "city" ],
     "metrics": [ "totalUsers" ],
     "mode": "table",
     "selectedDimensions": [
      {
       "description": "The city from which the user activity originated.",
       "label": "City",
       "value": "city"
      }
     ],
     "selectedMetrics": [
      {
       "description": "The number of distinct users who have logged at least one event, regardless of whether the site or app was in use when that event was logged.",
       "label": "Total users",
       "value": "totalUsers"
      }
     ],
     "timezone": "Etc/GMT",
     "version": "v4",
     "webPropertyId": "properties/336167131"
    }
   ]
  }
 ]
}